# Generated by Django 4.2 on 2023-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAutores',
            fields=[
                ('codigo_autor', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SearchConteudos',
            fields=[
                ('codigo_pub', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('texto', models.CharField(max_length=5000)),
                ('data_pub', models.DateTimeField(auto_now_add=True)),
                ('visibilidade', models.BooleanField(default=True)),
                ('codigo_autor', models.CharField(max_length=255)),
            ],
        ),
    ]
